Classroom.MVC/Controllers/ScienceController.cs
using Classroom.MVC.Helpers;
using Classroom.MVC.Models;
using ClassRoomData.Context;
using ClassRoomData.Entities;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;

namespace Classroom.MVC.Controllers;

public class SciencesController : Controller
{
    private readonly AppDbContext _context;
    private readonly UserProvider _userProvider;

    public SciencesController(AppDbContext context, UserProvider userProvider)
    {
        _context = context;
        _userProvider = userProvider;
    }

    public async Task<IActionResult> Index(Guid schoolId, string? name = null, bool orderByUsers = false)
    {
        /*var school = await _context.Schools
            .Include(s => s.Sciences)
            .ThenInclude(s => s.UserSciences)
            .FirstOrDefaultAsync(s => s.Id == schoolId);

        return View(school);*/
        var query = _context.Sciences
            .Include(s => s.UserSciences);


        ViewBag.SchoolId = schoolId;
        if (name == null)
        {
            var school = await _context.Schools
                .Include(s => s.Sciences)
                .ThenInclude(s => s.UserSciences)
                .FirstOrDefaultAsync(s => s.Id == schoolId);

            school = await _context.Schools
                .Include(s => s.UserSchools)
                .FirstOrDefaultAsync(s => s.Id == schoolId);

            if (school == null)
            {
                return RedirectToAction("Index", "Home");
            }

            return View(school);
        }
        else
        {
            var school = await _context.Schools
                .Include(s => s.Sciences.Where(s => s.Name.Contains(name)))
                .ThenInclude(s => s.UserSciences)
                .FirstOrDefaultAsync(s => s.Id == schoolId);

            school = await _context.Schools
                .Include(s => s.UserSchools)
                .FirstOrDefaultAsync(s => s.Id == schoolId);

            return View(school);
        }
    }

    public async Task<IActionResult> GetScienceById(Guid scienceId)
    {
        var science = await _context.Sciences
            .Include(s => s.School)
            .Include(s => s.UserSciences)
            .ThenInclude(s => s.User)
            .FirstOrDefaultAsync(s => s.Id == scienceId);

        return View(science);
    }


    [HttpGet]
    public IActionResult CreateScience(Guid schoolId)
    {
        ViewBag.SchoolId = schoolId;
        return View();
    }

    [HttpPost]
    public async Task<IActionResult> CreateScience(Guid schoolId, [FromForm] CreateScienceDto createDto)
    {
        if (!ModelState.IsValid)
        {
            return View(createDto);
        }
        var school = new Science()
        {
            Name = createDto.Name,
            Description = createDto.Description,
            SchoolId = schoolId
        };

        school.UserSciences = new List<UserScience>
        {
            new UserScience()
            {
                UserId = _userProvider.UserId,
                Type = EUserScience.Teacher
            }
        };

        _context.Sciences.Add(school);
        await _context.SaveChangesAsync();
        return RedirectToAction("Index", new { schoolId = schoolId });
    }

    [HttpGet]
    public IActionResult SendJoinScienceRequest(Guid scienceId)
    {
        ViewBag.ScienceId = scienceId;
        return View();
    }

    [HttpPost]
    public async Task<IActionResult> SendJoinScienceRequest(Guid scienceId,
        [FromForm] CreateJoinScienceRequestDto joinRequestDto)
    {
        var toUser = await _context.Users.FirstOrDefaultAsync(u => u.UserName == joinRequestDto.UserName);

        if (toUser == null)
        {
            return RedirectToAction("Index", "Schools");
        }
        var isExistsPreviewJoinRequest =
        await _context.JoinScienceRequests
                .AnyAsync(r => r.ToUserId == toUser.Id && r.ScienceId == scienceId);

        if (isExistsPreviewJoinRequest)
        {
            return RedirectToAction("GetScienceById", new { scienceId });
        }

        var isExistsInScience =
            await _context.UserSciences
                .AnyAsync(u => u.UserId == toUser.Id && u.ScienceId == scienceId);
        if (isExistsInScience)
        {
            return RedirectToAction("GetScienceById", new { scienceId });
        }

        var userId = _userProvider.UserId;

        var joinRequest = new JoinScienceRequest()
        {
            FromUserId = userId,
            ToUserId = toUser.Id,
            ScienceId = scienceId,
            IsJoined = false,

        };

        _context.JoinScienceRequests.Add(joinRequest);
        await _context.SaveChangesAsync();

        return RedirectToAction("GetScienceById", new { scienceId });
    }

    public async Task<IActionResult> JoinScience(bool isJoin, Guid joinRequestId)
    {
        var joinRequest = await _context.JoinScienceRequests.FirstOrDefaultAsync(u => u.Id == joinRequestId && u.ToUserId == _userProvider.UserId);
        if (isJoin)
        {
            var userScience = new UserScience()
            {
                ScienceId = joinRequest.ScienceId,
                UserId = joinRequest.ToUserId,
                Type = EUserScience.Student,
            };
            joinRequest.IsJoined = true;
            _context.UserSciences.Add(userScience);
        }
        else
        {
            _context.JoinScienceRequests.Remove(joinRequest);
        }
        await _context.SaveChangesAsync();
        return RedirectToAction("Profile", "Users");
    }

    // Remove funksiyasi yozilgan joy , get science by id da ham if li qismida buni front yozilgan
    public async Task<IActionResult> Remove(Guid scienceId, Guid Uid, Guid schoolId)
    {

        var s = await _context.UserSciences.FirstAsync(s => s.UserId == Uid && s.ScienceId == scienceId);

        _context.UserSciences.Remove(s);
        await _context.SaveChangesAsync();

        return RedirectToAction("GetScienceById", new { scienceId, schoolId });
    }


}

Classroom.MVC/Controllers/TasksController.cs
using Classroom.MVC.Helpers;
using Classroom.MVC.Models;
using ClassRoomData.Context;
using ClassRoomData.Entities;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;

namespace Classroom.MVC.Controllers;

public class TasksController : Controller
{
    private readonly AppDbContext _context;
    private readonly UserProvider _userProvider;

    public TasksController(AppDbContext context, UserProvider userProvider)
    {
        _context = context;
        _userProvider = userProvider;
    }

    public async Task<IActionResult> Index(Guid scienceId)
    {
        var tasks = await _context.TaskEntities
            .Where(t => t.ScienceId == scienceId)
            .ToListAsync();

        ViewBag.ScienceId = scienceId;
        return View(tasks);
    }

    [HttpGet]
    public IActionResult CreateScienceTask(Guid scienceId)
    {
        ViewBag.ScienceId = scienceId;
        return View();
    }

    [HttpPost]
    public async Task<IActionResult> CreateScienceTask([FromForm] CreateTaskDto createTaskDto, Guid scienceId)
    {
        var task = new TaskEntity()
        {
            Title = createTaskDto.Title,
            Description = createTaskDto.Description,
            StartDate = createTaskDto.StartDate,
            EndDate = createTaskDto.EndDate,
            Status = ETaskStatus.Active,
            MaxBall = createTaskDto.MaxBall,
            ScienceId = scienceId
        };

        _context.TaskEntities.Add(task);
        await _context.SaveChangesAsync();

        return RedirectToAction("Index", new { scienceId });
    }

    public async Task<IActionResult> GetTaskById(Guid taskId)
    {
        var task = await _context.TaskEntities
            .Include(t => t.Comments)
            .ThenInclude(c => c.User)
            .FirstOrDefaultAsync(t => t.Id == taskId);


        return View(task);
    }

    public async Task<IActionResult> AddComment(Guid taskId, [FromForm] CreateCommentDto commentDto)
    {
        var comment = new TaskComment()
        {
            Comment = commentDto.Comment,
            TaskId = taskId,
            UserId = _userProvider.UserId,
        };

        _context.TaskComments.Add(comment);
        await _context.SaveChangesAsync();

        return RedirectToAction("GetTaskById", new { taskId });
    }
}

Classroom.MVC/Views/Sciences/CreateScience.cshtml
@model CreateScienceDto

<div class="loginBox" style="margin :auto ; text-align : center ">
    <h3 style="color: blue ; margin :auto ; text-align : center ">Create School Here</h3>
    <form class="row g-3" style="width: 400px ; margin :auto ; text-align : center " asp-controller="Sciences" asp-action="CreateScience" asp-route-schoolId="@ViewBag.SchoolId" method="post" enctype="multipart/form-data">

        <div >
            <input name="Name" class="form-control" asp-for="Name"  type="text" placeholder="Name"/>
            <span class="text-danger" asp-validation-for="Name"> </span>
        </div>

        <div >
            <input name="Description" class="form-control" asp-for="Description"  type="text" placeholder="Description"/>
            <span class="text-danger" asp-validation-for="Description"> </span>
        </div>

        <button class="btn btn-primary form-control"  type="submit">Create Science</button>
    </form>
</div>

Classroom.MVC/Views/Sciences/GetScienceById.cshtml
@using ClassRoomData.Entities
@using Classroom.MVC.Helpers
@model ClassRoomData.Entities.Science
@inject UserProvider UserProvider   

<h1>Science</h1>
<h3>Name: @Model.Name</h3>
<h3>Description: @Model.Description</h3>
<h3>Teacher: @Model.UserSciences!.First(u => u.Type == EUserScience.Teacher).User?.UserName</h3>


<a class="btn btn-primary" asp-controller="Tasks" asp-action="Index" asp-route-scienceId="@Model.Id">Tasks</a>
@{
    var id = Model.UserSciences!.First(u => u.Type == EUserScience.Teacher).User?.Id;
    if (UserProvider.UserId == id)
    {
        <a class="btn btn-secondary" asp-action="SendJoinScienceRequest" asp-route-scienceId="@Model.Id">Send join request</a>
    }
}

<h1>Students</h1>
<table class="table">
    <thead>
    <tr>
        <th scope="col">#</th>
        <th scope="col">Firstname</th>
        <th scope="col">Username</th>
        <th scope="col">Role</th>
            <th scope="col">Remove</th>
    </tr>
    </thead>
    <tbody>
    @{
        for (var i = 0; i < Model.UserSciences!.Count; i++)
        {
            var userSchool = Model.UserSciences[i];
            <tr>
                <th scope="row">@(i + 1)</th>
                <td>@userSchool.User.FirstName</td>
                <td>@userSchool.User.UserName</td>
                <td>@userSchool.Type</td>
                
                    <td>
                        @if (userSchool.Type == EUserScience.Student && @Model.UserSciences!.First(u => u.Type == EUserScience.Teacher).User?.Id == UserProvider.UserId)
                        {
                            <a class="btn btn-primary" style="color : red" asp-action="RemoveStudent" asp-route-userId="@userSchool.User.Id" asp-route-scienceId="@Model.Id" asp-route-schoolid="@ViewBag.SchoolId">Remove</a>
                        }
                        else
                        {
                            <h3> ✅ </h3>
                        }
                    </td>

            </tr>
        }
    }
    </tbody>
</table>

Classroom.MVC/Views/Sciences/Index.cshtml
@using Classroom.MVC.Helpers;
@model ClassRoomData.Entities.School
@inject UserProvider userProvider

<div style="display: flex; align-items: center; gap: 18rem">
    <div>
        <h1>Sciences </h1>
        <a class="btn btn-primary" asp-area="" asp-action="CreateScience" asp-route-schoolId="@ViewBag.SchoolId">Create</a>
    </div>
    <div>
        <form class="row g-3" style="display: flex; flex-direction: column" asp-action="Index" asp-route-schoolId="@ViewBag.SchoolId" method="get">
            <div class="input-group">
                <input type="hidden" name="SchoolId" value="@ViewBag.SchoolId">
                <input type="text" name="Name" class="form-control" placeholder="Science's name" aria-label="Science's name" aria-describedby="basic-addon2">
                <div class="input-group-append">
                    <button class="btn btn-outline-secondary" type="submit">Search</button>
                </div>
            </div>
        </form>
    </div>
</div>


<table class="table">
    <thead>
    <tr>
        <th scope="col">#</th>
        <th scope="col">Name</th>
        <th scope="col">Description</th>
        <th scope="col">Users</th>
        <th scope="col">View</th>
    </tr>
    </thead>
    <tbody>
    @for (var i = 0; i < Model.Sciences?.Count; i++)
    {
        var science = Model.Sciences[i];

        <tr>
            <th scope="row">@(i + 1)</th>
            <td>@science.Name</td>
            <td>@science.Description</td>
            <td>@science.UserSciences?.Count</td>
            <td>
                <a class="btn btn-primary" asp-action="GetScienceById" asp-route-scienceId="@science.Id" asp-route-schoolId="@Model.Id">View</a>
            </td>
        </tr>
    }
    </tbody>
</table>

Classroom.MVC/Views/Sciences/SendJoinScienceRequest.cshtml
@model CreateJoinScienceRequestDto

@{
    ViewData["Title"] = "Send Join Science Request";
}

<h1 style="margin: auto; text-align: center">Send Join Science Request</h1>
<form class="row g-3" style="width: 400px; margin: auto" asp-action="SendJoinScienceRequest" asp-route-scienceId="@ViewBag.ScienceId" method="post">
    <div>
        <input name="Username" class="form-control" asp-for="UserName" type="text" placeholder="Username" />
        <span class="text-danger" asp-validation-for="UserName"></span>
    </div>
    <button class="form-control" type="submit">Send join request</button>
</form>