Classroom.MVC/Controllers/HomeController.cs
using Classroom.MVC.Models;
using ClassRoomData.Context;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using System.Diagnostics;

namespace Classroom.MVC.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;
        private readonly AppDbContext _context;

        public HomeController(ILogger<HomeController> logger, AppDbContext context)
        {
            _logger = logger;
            _context = context;
        }

        public async Task<IActionResult> Index()
        {
            var schools = await _context.Schools
                .Include(school => school.UserSchools)
                .ToListAsync();
            return View(schools);
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

Classroom.MVC/Controllers/SchoolsController.cs
using Classroom.MVC.Helpers;
using Classroom.MVC.Models;
using ClassRoomData.Context;
using ClassRoomData.Entities;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;

namespace Classroom.MVC.Controllers;

public class SchoolsController : Controller
{
    private readonly AppDbContext _context;
    private readonly UserProvider _userProvider;

    public SchoolsController(AppDbContext context, UserProvider userProvider)
    {
        _context = context;
        _userProvider = userProvider;
    }

    [HttpGet]
    public IActionResult CreateSchool()
    {
        return View();
    }

    [HttpPost]
    public async Task<IActionResult> CreateSchool([FromForm] CreateSchoolDto createschool)
    {
        /*
         if (!ModelState.IsValid)
        {
            return View(createschool);
        }
        */

        var school = new School()
        {
            Name = createschool.Name,
            Description = createschool.Description,
        };

        if (createschool.LogoPhoto != null)
        {
            school.LogoUrl = await FileHelper.SaveSchoolFile(createschool.LogoPhoto);
        }
        school.UserSchools = new List<UserSchool>()
        {
            new UserSchool()
            {
                UserId = _userProvider.UserId,
                Type = EUserSchool.Founder,
            }
        };

        _context.Schools.Add(school);
        await _context.SaveChangesAsync();
        return RedirectToAction("Index", "Home");
    }

    public async Task<IActionResult> Index()
    {
        var schools = await _context.Schools
            .Include(school => school.UserSchools)
            .ToListAsync();
        return View(schools);
    }


    public async Task<IActionResult> GetSchoolById(Guid id)
    {
        var userId = _userProvider.UserId;
        if (userId == null)
        {
            return RedirectToAction("SignUp", "Users");
        }
        var school = await _context.Schools
            .Include(school => school.UserSchools)
                .ThenInclude(userschool => userschool.User)
                    .FirstOrDefaultAsync(x => x.Id == id);

        return View(school);
    }

    public async Task<IActionResult> JoinSchool(Guid id)
    {
        var school = await _context.Schools
                     .Include(school => school.UserSchools)
                        .ThenInclude(u => u.User)
                            .FirstOrDefaultAsync(userschool => userschool.Id == id);

        var userId = _userProvider.UserId;
        if (!school.UserSchools.Any(u => u.User.Id == userId))
        {
            school.UserSchools.Add(new UserSchool()
            {
                UserId = userId,
                Type = EUserSchool.student,
            });
        }

        /*var userschool = new UserSchool()
        {
            UserId = userId,
            SchoolId = id,
            Type = EUserSchool.student
        };*/
        await _context.SaveChangesAsync();
        return RedirectToAction("GetSchoolById", new { id = school.Id });
    }


    [HttpGet]
    public async Task<IActionResult> UpdateSchool(Guid id)
    {
        var school = await _context.Schools
            .Include(school => school.UserSchools)
            .ThenInclude(userschool => userschool.User)
            .FirstOrDefaultAsync(x => x.Id == id);

        ViewBag.Id = id;
        return View(new UpdateSchoolDto()
        {
            Name = school.Name,
            Description = school.Description,
        });
    }

    [HttpPost]
    public async Task<IActionResult> UpdateSchool(Guid id, [FromForm] UpdateSchoolDto updateschool)
    {
        var school = await _context.Schools.FirstOrDefaultAsync(u => u.Id == id);

        school.Name = updateschool.Name;
        school.Description = updateschool.Description;
        if (updateschool.LogoPhoto != null)
        {
            school.LogoUrl = await FileHelper.SaveSchoolFile(updateschool.LogoPhoto);
        }

        await _context.SaveChangesAsync();

        return RedirectToAction("GetSchoolById", new { id = school.Id });
    }


    public async Task<IActionResult> UpdateUserRole(Guid schoolId, Guid userId, EUserSchool role)
    {
        var userSchool = await _context.UserSchools
            .FirstOrDefaultAsync(u => u.UserId == userId && u.SchoolId == schoolId);

        if (userSchool.Type != EUserSchool.Founder && role != EUserSchool.Founder)
            userSchool.Type = role;

        await _context.SaveChangesAsync();

        return RedirectToAction("GetSchoolById", new { id = schoolId });
    }
}

Classroom.MVC/Controllers/UsersController.cs
using Classroom.MVC.Helpers;
using Classroom.MVC.Models;
using ClassRoomData.Context;
using ClassRoomData.Entities;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;

namespace Classroom.MVC.Controllers;

public class UsersController : Controller
{
    private readonly UserManager<User> _usermanager;
    private readonly SignInManager<User> _signInManager;
    private readonly AppDbContext _context;

    public UsersController(UserManager<User> usermanager, SignInManager<User> signInManager, AppDbContext context)
    {
        _usermanager = usermanager;
        _signInManager = signInManager;
        _context = context;
    }

    [HttpGet]
    public IActionResult SignUp()
    {
        return View();
    }

    [HttpPost]
    public async Task<IActionResult> SignUp([FromForm] CreateUserDto model)
    {
        if (!ModelState.IsValid)
        {
            return View(model);
        }

        var user = new User()
        {
            FirstName = model.FirstName,
            UserName = model.UserName,
            Email = model.Email,
            PhoneNumber = model.PhoneNumber,
            Age = model.Age,
        };

        user.PhotoUrl = await FileHelper.SaveUserFile(model.Photo);

        var result = await _usermanager.CreateAsync(user, model.Password);

        if (!result.Succeeded)
        {
            ModelState.AddModelError("Username", result.Errors.First().Description);

            return View();
        }
        await _signInManager.SignInAsync(user, isPersistent: true);

        return RedirectToAction("Profile");
    }


    [Authorize]
    public async Task<IActionResult> Profile()
    {
        var user = await _usermanager.GetUserAsync(User);
        return View(user);
    }


    [HttpGet]
    public IActionResult SignIn()
    {
        return View();
    }


    [HttpPost]
    public async Task<IActionResult> SignIn([FromForm] SigninUserDto signinUserDto)
    {
        var result = await _signInManager.PasswordSignInAsync(signinUserDto.UserName, signinUserDto.Password, true, false);
        if (!result.Succeeded)
        {
            ModelState.AddModelError("UserName", " UserName or Password is not found");
            return View();
        }


        return RedirectToAction("Profile");
    }


    [Authorize]
    public async Task<IActionResult> LogOut()
    {
        await _signInManager.SignOutAsync();
        return RedirectToAction("Index", "Home");
    }

    ///    update user
    [HttpGet]
    public async Task<IActionResult> UpdateUser(Guid id)
    {
        var user = await _context.Users
            .FirstOrDefaultAsync(x => x.Id == id);

        if (user == null)
        {
            return RedirectToAction("SignUp");
        }

        ViewBag.Id = id;

        return View();
    }


    [HttpPost]
    public async Task<IActionResult> UpdateUser(Guid id, [FromForm] UpdateUserDto updateUserDto)
    {
        var user = await _context.Users.FirstOrDefaultAsync(u => u.Id == id);

        if (user == null)
        {
            return RedirectToAction("SignUp");
        }

        user.FirstName = updateUserDto.FirstName;
        user.UserName = updateUserDto.UserName;

        if (updateUserDto.UserPhoto != null)
        {
            user.PhotoUrl = await FileHelper.SaveSchoolFile(updateUserDto.UserPhoto);
        }

        await _context.SaveChangesAsync();

        return RedirectToAction("Profile");
    }

}

Classroom.MVC/Views/Home/Index.cshtml
@using System.Security.Claims;
@{
    ViewData["Title"] = "Home Page";
}

@model List<ClassRoomData.Entities.School>

<h1 style="align-content: center"> Schools </h1>
@*
<table class="table table-striped table-hover">
    <thread>
        <tr> 
            <th scope="col">#</th>
            <th scope="col">Name</th>
            <th scope="col">Description</th>
            <th scope="col">Users</th>
            <th scope="col">Show</th>
        </tr>
    </thread>
    <tbody>
    @for(var i = 0 ; i < Model.Count ; i++)
    {
        var school = Model[i];
        <tr>
            <th scope="col">@(i+1)</th>
            <td >@school.Name</td>
            <td >@school.Description</td>
            <td >@school.UserSchools?.Count</td>
            <td >
                    @if(User.HasClaim(claim => claim.Type == ClaimTypes.NameIdentifier))
                    {
                        <a class="btn btn-primary" asp-controller="Schools" asp-action="GetSchoolById" asp-route-id="@school.Id">
                            Show School
                        </a>
                    }
                    else
                    {
                     <a  class="btn btn-primary" asp-controller="Users" asp-action="SignUp"> 
                      Show School
                     </a>
                    }
            </td>
        </tr>
    }
    </tbody>
</table>
*@

<div class="row col-lg-12 col-md-12 col-sm-12 gap-3 d-flex justify-content-center">


    @for (var i = 0; i < Model.Count; i++)
    {
        var school = Model[i];

        <div class="card" style="width: 30%;box-shadow: 0 0rem 3rem rgba(8,7,16,0.6)!important;">
            <img src="@school.LogoUrl" class="card-img-top" alt="RASM">
            <div class="card-body">
                <h4 class="card-title">Name: @school.Name</h4>
                <h5>Users Count: @school.UserSchools?.Count</h5>
                <p class="card-text">Description: @school.Description</p>
                @if (User.HasClaim(claim => claim.Type == ClaimTypes.NameIdentifier))
                {
                    <a class="btn btn-primary" asp-controller="Schools" asp-action="GetSchoolById" asp-route-id="@school.Id">
                        Show School
                    </a>
                }
                else
                {
                    <a class="btn btn-primary" asp-controller="Users" asp-action="SignUp">
                        Show School
                    </a>
                }
            </div>
        </div>
    }
</div>